version: 2

jobs:
  Node10 tests:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: node --version > node_version
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "node_version" }}-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-packages-{{ checksum "node_version" }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn test

  Node12 tests:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: node --version > node_version
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "node_version" }}-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-packages-{{ checksum "node_version" }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn test
      - run: curl -s https://codecov.io/bash | bash

  Release:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: node --version > node_version
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "node_version" }}-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-packages-{{ checksum "node_version" }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: |
          git config --global user.email deploy@travis-ci.org
          git config --global user.name Deployment Bot
          git remote set-url origin "https://${GH_TOKEN}@github.com/nodkz/mongodb-memory-server.git" > /dev/null 2>&1
          git checkout master
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ${HOME}/.npmrc 2> /dev/null
      - run: yarn build
      - run: yarn release --yes

workflows:
  version: 2
  build:
    jobs:
      - Node10 tests
      - Node12 tests
      - Release:
          requires:
            - Node10 tests
            - Node12 tests
          filters:
            branches:
              only: master
