# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # TODO: replace "17.x" with "18.x" when 18 releases
        node-version: [12.x, 14.x, 16.x, 17.x]
    steps:
      - uses: actions/checkout@v3
        if: github.event.inputs.git-ref == ''
        with:
          fetch-depth: 0 # always fetch everything to be sure for codecov
      - uses: actions/checkout@v3
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}
          fetch-depth: 5 # because this is an manual trigger, only fetch the latest 5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install node_modules
        run: yarn
      - name: TSCheck
        run: yarn --cwd packages/mongodb-memory-server-core run tscheck
      - name: ESLint
        run: yarn run lint
      - name: Tests
        run: yarn --cwd packages/mongodb-memory-server-core run coverage --colors
        env:
          CI: true
      - name: Send codecov.io stats
        if: matrix.node-version == '12.x'
        uses: codecov/codecov-action@v2

  publish:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/beta' || startsWith(github.ref, 'refs/heads/old')
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Install node_modules
        run: yarn install
      - name: Build
        run: yarn build
      - name: Semantic Release (publish to npm)
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
